import {
  FaBuilding,
  FaGraduationCap,
  FaHandHoldingUsd,
  FaHandshake,
  FaHourglassEnd,
  FaList,
  FaRegCreditCard,
  FaSignal,
  FaSitemap,
  FaSlack,
  FaUserClock,
  FaUserGraduate,
  FaUsers,
  FaUserShield,
} from "react-icons/fa"
import { FaUserGear, FaUsersViewfinder, FaUser, FaUserGroup } from "react-icons/fa6"
import {
  AdminPage,
  Students,
  OneStudent,
  Speciality,
  PaymentHistory,
  TransactionHistory,
  PaymentDetails,
  StudentStatistics,
  PmGroupController,
  OnePaymentGroup,
  GroupStatistics,
  GroupList,
  GroupStudents,
  Role,
  Debt,
  Discount,
  UniversityStatistics,
  SpecialityStatistics,
  PaymentHistoryChart,
  Xazna,
  Abiturient,
  Log,
  SpecialityForm,
} from "@modules"
import { FiSlack } from "react-icons/fi"

export const routesConfig = [
  {
    label: "Admin va ruxsatlar",
    icon: <FaUser style={{ fontSize: "22px" }} />,
    showInSidebar: true,
    permissions: ["ADMIN_ROLE_MENU", "ADMIN_USER_MENU"],
    children: [
      {
        path: "admin-permissions",
        icon: <FaUserGear style={{ fontSize: "22px" }} />,
        label: "Rol va ruxsatlar",
        element: <Role />,
        permissions: ["ADMIN_ROLE_MENU"],
        showInSidebar: true,
      },
      {
        path: "admin-page",
        icon: <FaUserShield style={{ fontSize: "22px" }} />,
        label: "Admin User",
        element: <AdminPage />,
        permissions: ["ADMIN_USER_MENU"],
        showInSidebar: true,
      },
    ],
  },

  {
    label: "Ro'yxatlar",
    icon: <FaList style={{ fontSize: "22px" }} />,
    showInSidebar: true,
    permissions: ["STUDENT_MENU", "STUDENT_HEMIS_LIST", "STUDENT_MENU"],
    children: [
      {
        path: "students",
        label: "Studentlar",
        icon: <FaUserGraduate style={{ fontSize: "22px" }} />,
        element: <Students />,
        permissions: ["STUDENT_MENU"],
        showInSidebar: true,
      },
      {
        path: "students/:id",
        element: <OneStudent />,
        permissions: ["STUDENT_MENU"],
        showInSidebar: false,
      },
      {
        path: "abiturients",
        label: "Abiturientlar",
        icon: <FaUserClock style={{ fontSize: "22px" }} />,
        element: <Abiturient />,
        permissions: ["STUDENT_HEMIS_LIST"],
        showInSidebar: true,
      },
      {
        path: "speciality",
        label: "Yo'nalishlar",
        icon: <FaSlack style={{ fontSize: "22px" }} />,
        element: <Speciality />,
        permissions: ["SPECIALITY_MENU"],
        showInSidebar: true,
      },
      {
        path: "speciality/:id",
        element: <SpecialityForm />,
        permissions: ["SPECIALITY_MENU"],
        showInSidebar: false,
      },
      {
        path: "group-list",
        label: "Guruhlar",
        icon: <FaUsers style={{ fontSize: "22px" }} />,
        element: <GroupList />,
        permissions: ["GROUP_MENU"],
        showInSidebar: true,
      },
    ],
  },
  {
    label: "To'lovlar",
    icon: <FaRegCreditCard style={{ fontSize: "22px" }} />,
    showInSidebar: true,
    permissions: ["PAYMENT_GROUP_MENU", "TRANSACTION_MENU", "DISCOUNT_PAGEABLE"],
    children: [
      {
        path: "pmgroup-controller",
        icon: <FaUsersViewfinder style={{ fontSize: "22px" }} />,
        label: "To'lov guruhlari",
        element: <PmGroupController />,
        permissions: ["PAYMENT_GROUP_MENU"],
        showInSidebar: true,
      },
      {
        path: "transaction-history",
        icon: <FaHourglassEnd style={{ fontSize: "22px" }} />,
        label: "Tranzaksiyalar",
        element: <TransactionHistory />,
        permissions: ["TRANSACTION_MENU"],
        showInSidebar: true,
      },
      {
        path: "payment-history",
        icon: <FaRegCreditCard style={{ fontSize: "22px" }} />,
        label: "Click",
        element: <PaymentHistory />,
        permissions: ["CLICK_PAYMENT_HISTORY"],
        showInSidebar: true,
      },
      {
        path: "xazna",
        label: "Xazna",
        icon: <FaRegCreditCard style={{ fontSize: "22px" }} />,
        element: <Xazna />,
        permissions: ["XAZNA_PAYMENT_HISTORY"],
        showInSidebar: true,
      },
      {
        path: "debt",
        icon: <FaHandshake style={{ fontSize: "22px" }} />,
        label: "Qo'shimcha qarzdorlik",
        element: <Debt />,
        permissions: ["DISCOUNT_PAGEABLE"],
        showInSidebar: true,
      },
      {
        path: "discounts",
        icon: <FaHandHoldingUsd style={{ fontSize: "22px" }} />,
        label: "Chegirmalar",
        element: <Discount />,
        permissions: ["DISCOUNT_PAGEABLE"],
        showInSidebar: true,
      },
      {
        path: "log",
        icon: <FaSitemap style={{ fontSize: "22px" }} />,
        label: "Log",
        element: <Log />,
        permissions: ["DISCOUNT_PAGEABLE"],
        showInSidebar: true,
      },
    ],
  },

  {
    path: "pmgroup-controller/:id",
    element: <OnePaymentGroup />,
    permissions: ["PAYMENT_GROUP_MENU"],
    showInSidebar: false,
  },
  {
    path: "payment-history",
    label: "Click",
    icon: <FaRegCreditCard style={{ fontSize: "22px" }} />,
    element: <PaymentHistory />,
    permissions: ["PAYMENT_MENU"],
    showInSidebar: true,
  },

  {
    path: "transaction-history/:id",
    element: <PaymentDetails />,
    permissions: ["TRANSACTION_MENU"],
    showInSidebar: false,
  },
  {
    label: "Statistikalar",
    icon: <FaSignal style={{ fontSize: "22px" }} />,
    showInSidebar: true,
    permissions: ["GROUP_STATISTICS_MENU", "STUDENT_STATISTICS_MENU"],
    children: [
      {
        path: "university-statistics",
        label: "Universitet",
        icon: <FaBuilding style={{ fontSize: "22px" }} />,
        element: <UniversityStatistics />,
        permissions: ["UNIVERSITY_STATISTICS"],
        showInSidebar: true,
      },
      {
        path: "speciality-statistics",
        label: "Yo'nalishlar",
        icon: <FiSlack style={{ fontSize: "22px" }} />,
        element: <SpecialityStatistics />,
        permissions: ["SPECIALITY_FORM_STATISTICS_PAGEABLE"],
        showInSidebar: true,
      },
      {
        path: "group-statistics",
        label: "Guruhlar",
        icon: <FaUserGroup style={{ fontSize: "22px" }} />,
        element: <GroupStatistics />,
        permissions: ["GROUP_STATISTICS_MENU"],
        showInSidebar: true,
      },
      {
        path: "payment-chart",
        label: "To'lov",
        icon: <FaUserGroup style={{ fontSize: "22px" }} />,
        element: <PaymentHistoryChart />,
        permissions: ["TRANSACTION_STATISTICS_GRAPH_MENU"],
        showInSidebar: true,
      },
      {
        path: "students-statistics",
        label: "Studentlar",
        icon: <FaGraduationCap style={{ fontSize: "22px" }} />,
        element: <StudentStatistics />,
        permissions: ["STUDENT_STATISTICS_MENU"],
        showInSidebar: true,
      },
    ],
  },

  {
    path: "group-statistics/:id",
    element: <GroupStudents />,
    permissions: ["GROUP_STATISTICS_MENU"],
    showInSidebar: false,
  },
]
