export enum Permissions {
    ADMIN_ROLE_MENU = "ADMIN_ROLE_MENU",
    ADMIN_USER_MENU = "ADMIN_USER_MENU",
    STUDENT_MENU = "STUDENT_MENU",
    SPECIALITY_MENU = "SPECIALITY_MENU",
    GROUP_MENU = "GROUP_MENU",
    PAYMENT_GROUP_MENU = "PAYMENT_GROUP_MENU",
    PAYMENT_MENU = "PAYMENT_MENU",
    TRANSACTION_MENU = "TRANSACTION_MENU",
    STUDENT_STATISTICS_MENU = "STUDENT_STATISTICS_MENU",
    GROUP_STATISTICS_MENU = "GROUP_STATISTICS_MENU",
}